FROM golang
MAINTAINER Dexter Yan

RUN apt-get update                                                            && \
    apt-get install -y git cmake python-dev curl python python-pip ncurses-dev     && \
    rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/vim/vim.git ~/vim
RUN cd ~/vim                                                      && \
    ./configure --with-features=huge \
            --enable-multibyte \
            --enable-pythoninterp=yes \
            --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu/ \
            --enable-gui=gtk2 --enable-cscope --prefix=/usr     && \
    make VIMRUNTIMEDIR=/usr/share/vim/vim80                     && \
    make install


RUN git clone https://github.com/gmarik/Vundle.vim.git /root/.vim/bundle/Vundle.vim

RUN mkdir ~/.vim/colors
RUN curl -o ~/.vim/colors/monoacc.vim https://raw.githubusercontent.com/flazz/vim-colorschemes/master/colors/monoacc.vim

 # VIM
 COPY vimrc /root/.vimrc
 RUN vim +PluginInstall  +qall
 RUN vim +GoInstallBinaries +qall

 RUN cd ~/.vim/bundle/YouCompleteMe         && \
     ./install.py  --gocode-completer

 CMD ["/bin/bash"]
